# Site settings
name: Mike Owino
title: Mike Owino | Full-Stack Developer
description: Design-minded Full-Stack Developer focused on building beautiful interfaces and experiences
url: https://mikeowino.com/
baseurl: ''
email: mike@mikeowino.com
cover: https://mikeowino.com/img/og.png
logo: https://mikeowino.com/img/emojis/technologist.png
resume: https://mikeowino.com/resume.pdf
social:
  - title: email
    url: mailto:mike@mikeowino.com
  - title: twitter
    url: https://twitter.com/mikeeowino
  # - title: instagram
    # url: https://instagram.com/mikeeowino
  - title: codepen
    url: http://codepen.io/mikeowino
  - title: github
    url: https://github.com/mikeyhodl
  # - title: linkedin
    # url: https://www.linkedin.com/in/mikeeowino

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
